### ISSUE TITLE
"unresolved dependencies" should not log a stack trace

### ISSUE THREAD

**Issue by retronym** [sbt/librarymanagement#212]
```
warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.eed3si9n:sbt-buildinfo:0.6.1 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.eed3si9n:sbt-buildinfo:0.6.1 (scalaVersion=2.12, sbtVersion=1.0) (/Users/jz/code/scala/project/project/plugins.sbt#L1-2)
[warn] 		  +- default:scala-build-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-buildinfo;0.6.1: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2383)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException:
```

This is an everyday error and the user is not interested in the stack trace of SBT internals.

**Comment by 94ju** [comment]
i also came across the same error ,how to solve this

**Comment by SethTisue** [comment]
@94ju are you asking for help constructing a pull request that fixes it...?

**Comment by 94ju** [comment]
Yes i need some help

**Comment by SethTisue** [comment]
okay — how far'd you get? where'd you get stuck?

**Comment by 94ju** [comment]
I cannot enable ebean orm
Some problems came when configuring

Its a great help if you can help

On 5 Mar 2018 11:12 pm, "Seth Tisue" <notifications@github.com> wrote:

okay — how far'd you get? where'd you get stuck?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sbt/librarymanagement/issues/212#issuecomment-370501614>,
or mute the thread

**Comment by 94ju** [comment]
this is the error message


<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

**Comment by dwijnand** [comment]
hi @94ju,

please don't use the issue tracker to ask for help on how to use sbt, see https://www.scala-sbt.org/support.html.

**Comment by SethTisue** [comment]
to anyone who comes to this ticket searching for `sbt.librarymanagement.ResolveException`: this ticket is about how sbt ought to suppress printing a stack trace. it isn't about what might have caused the exception. please seek elsewhere for that

**Comment by eed3si9n** [comment]
Note to a contributor: This is related to the notion called `traceLevel`, 
"The amount of a stack trace displayed." There's a code somewhere that sets it in Defaults.scala.

In 2012 https://github.com/sbt/sbt/commit/dc2aaaf7ac80f2bc28ed76acdd76aa42342e693e the default was set as follows:

```diff
+	def defaultTraceLevel(state: State): Int =
+		if(state.interactive) -1 else Int.MaxValue
```

See also https://github.com/sbt/sbt/blob/v1.1.1/main/src/main/scala/sbt/internal/LibraryManagement.scala#L109
See https://github.com/sbt/util/blob/1.x/internal/util-logging/src/main/scala/sbt/internal/util/ConsoleAppender.scala
See https://github.com/sbt/util/blob/1.x/internal/util-logging/src/main/scala/sbt/internal/util/StackTrace.scala

```scala

   * Return a printable representation of the stack trace associated
   * with t.  Information about t and its Throwable causes is included.
   * The number of lines to be included for each Throwable is configured
   * via d which should be greater than or equal to 0.
   *
   * - If d is 0, then all elements are included up to (but not including)
   *   the first element that comes from sbt.
   * - If d is greater than 0, then up to that many lines are included,
   *   where the line for the Throwable is counted plus one line for each stack element.
   *   Less lines will be included if there are not enough stack elements.
   */
```

**Comment by eed3si9n** [comment]
Another thing to test for contributor. See if the behavior changes if you run from sbt shell or batch mode.

**Comment by exoego** [comment]
Is it sufficient to extend `ResolveException` with ` scala.util.control.NoStackTrace` ?

**Comment by dwijnand** [comment]
Maybe.  sbt also has another marker trait it uses, something like "MessageOnlyException".

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4965
