### ISSUE TITLE
cached resolution: mockito tests broken

### ISSUE THREAD

**Issue by edrevo** [sbt/librarymanagement#286]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

I have a set of tests that use mockito, which work just fine on sbt 1.2.4 and lower. Just bumping the version of sbt to 1.2.6, 1.2.7 or 1.2.8 will make the test fail with the following stack trace:

```
[info] com.telefonica.baikal.i18n.provisioners.PiScopeI18nProvisionerTest *** ABORTED ***
[info]   java.lang.NoSuchMethodError: org.mockito.internal.invocation.ArgumentsProcessor.expandArgs(Lorg/mockito/internal/invocation/MockitoMethod;[Ljava/lang/Object;)[Ljava/lang/Object;
[info]   at org.mockito.internal.invocation.InterceptedInvocation.<init>(InterceptedInvocation.java:44)
[info]   at org.mockito.internal.invocation.DefaultInvocationFactory.createInvocation(DefaultInvocationFactory.java:42)
[info]   at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63)
[info]   at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
[info]   at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:128)
[info]   at com.telefonica.baikal.i18n.services.I18nTermsService$MockitoMock$1879364830.publish(Unknown Source)
[info]   at com.telefonica.baikal.i18n.provisioners.PiScopeI18nProvisionerTest.$anonfun$new$1(PiScopeI18nProvisionerTest.scala:39)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[error] Uncaught exception when running com.telefonica.baikal.i18n.provisioners.PiScopeI18nProvisionerTest: java.lang.NoSuchMethodError: org.mockito.internal.invocation.ArgumentsProcessor.expandArgs(Lorg/mockito/internal/invocation/MockitoMethod;[Ljava/lang/Object;)[Ljava/lang/Object;
[error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: org.mockito.internal.invocation.ArgumentsProcessor.expandArgs(Lorg/mockito/internal/invocation/MockitoMethod;[Ljava/lang/Object;)[Ljava/lang/Object;
[error]         at org.mockito.internal.invocation.InterceptedInvocation.<init>(InterceptedInvocation.java:44)
[error]         at org.mockito.internal.invocation.DefaultInvocationFactory.createInvocation(DefaultInvocationFactory.java:42)
[error]         at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63)
[error]         at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
[error]         at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:128)
[error]         at com.telefonica.baikal.i18n.services.I18nTermsService$MockitoMock$1879364830.publish(Unknown Source)
[error]         at com.telefonica.baikal.i18n.provisioners.PiScopeI18nProvisionerTest.$anonfun$new$1(PiScopeI18nProvisionerTest.scala:39)
[error]         at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[error]         at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[error]         at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error]         at org.scalatest.Transformer.apply(Transformer.scala:22)
[error]         at org.scalatest.Transformer.apply(Transformer.scala:20)
[error]         at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[error]         at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[error]         at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[error]         at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
[error]         at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
[error]         at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
[error]         at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[error]         at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
[error]         at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
[error]         at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
[error]         at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
[error]         at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error]         at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[error]         at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[error]         at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
[error]         at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
[error]         at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
[error]         at org.scalatest.Suite.run(Suite.scala:1147)
[error]         at org.scalatest.Suite.run$(Suite.scala:1129)
[error]         at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
[error]         at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
[error]         at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[error]         at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
[error]         at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
[error]         at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
[error]         at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[error]         at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[error]         at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
```

The offending line is this one:

```scala
given(termsService.publish(contextName, toPublish)).willReturn(Future.successful(()))
```

here's the definition of each variable:

```scala
private val termsService = mock[I18nTermsService]
private val contextName: String = "PiScope-event123"
private val toPublish: Map[String, String] = Map("title" -> title, "description" -> description)
```

I am running on scala 2.12.8, using `"org.mockito" % "mockito-core" % "2.23.4"` and `"org.scalatest" %% "scalatest" % "3.0.5"`.

The SBT definition of the project with the failing tests is the following:

```scala
lazy val i18n = (project in file ("i18n"))
  .enablePlugins(PlayScala)
  .enablePlugins(BuildInfoPlugin)
  .settings(buildInfoSettings)
  .settings(
    name := "i18n",
    libraryDependencies ++= i18nDependencies,
    parallelExecution in Test := false, // mockito and multithreading aren't friends
  )
  .dependsOn(common % "compile->compile;test->test")
  .dependsOn(slickExtensions)
  .dependsOn(services)

lazy val root = (project in file("."))
  .settings(
    inThisBuild(
      List(
        organization := "com.telefonica.baikal",
        scalaVersion := "2.12.8",
        fork in Test := true,
        updateOptions := updateOptions.value.withCachedResolution(true)
      )
    )
  )
```

**Comment by edrevo** [comment]
Without cached resolution everything seems to work fine. Thanks!

**Comment by eed3si9n** [comment]
Closing this for now.

**Comment by tnielens** [comment]
I've reproduced this. It doens't seem related to sbt in my case. The issue is that org.spec2.spec2-mock includes mockito packages, including `org.mockito.internal.invocation.ArgumentsProcessor`. Older versions of this class don't have the `expandArgs` method. That causes the linkage error.

The versions I use: 
org.specs2:specs2-mock_2.11:3.8.9
org.mockito:mockito-core:3.5.13
